// Shared Prisma select for the seller cabinet: full order info incl. buyer
// contacts, delivery address and internal note.
export const adminOrderSelect = {
  id: true,
  orderNumber: true,
  status: true,
  total: true,
  subtotal: true,
  deliveryCost: true,
  discount: true,
  promoCode: true,
  channel: true,
  deliveryProvider: true,
  deliveryMethod: true,
  deliveryAddress: true,
  deliveryTrack: true,
  deliveryStatus: true,
  paymentMethod: true,
  paymentStatus: true,
  customerName: true,
  customerEmail: true,
  customerPhone: true,
  customerComment: true,
  adminNote: true,
  createdAt: true,
  updatedAt: true,
  items: {
    select: {
      id: true,
      productId: true,
      variantId: true,
      quantity: true,
      price: true,
      name: true,
      image: true,
      product: { select: { slug: true } },
    },
  },
} as const;
