CREATE TABLE products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug VARCHAR UNIQUE NOT NULL,
  name VARCHAR NOT NULL,
  description TEXT,
  short_description VARCHAR(200),
  price DECIMAL(10, 2) NOT NULL,
  price_old DECIMAL(10, 2),
  discount_percent INT,
  brand VARCHAR NOT NULL,
  product_line_id UUID NOT NULL REFERENCES product_lines(id),
  category_id UUID REFERENCES categories(id),
  images TEXT[] NOT NULL DEFAULT '{}',
  video_url VARCHAR,
  characteristics JSONB DEFAULT '{}',
  variants JSONB DEFAULT '[]',
  weight_grams INT NOT NULL DEFAULT 300,
  dimensions JSONB,
  stock INT DEFAULT 0,
  badge VARCHAR,
  rating DECIMAL(2, 1) DEFAULT 0,
  reviews_count INT DEFAULT 0,
  marketplace_ids JSONB DEFAULT '{}',
  seo_title VARCHAR(70),
  seo_description VARCHAR(160),
  seo_og_image VARCHAR,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);
