CREATE TABLE orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number SERIAL UNIQUE,
  user_id UUID REFERENCES auth.users(id),
  channel VARCHAR DEFAULT 'site',
  status VARCHAR DEFAULT 'pending',
  total DECIMAL(10, 2) NOT NULL,
  subtotal DECIMAL(10, 2) NOT NULL,
  delivery_cost DECIMAL(10, 2) DEFAULT 0,
  discount DECIMAL(10, 2) DEFAULT 0,
  promo_code VARCHAR,
  delivery_provider VARCHAR,
  delivery_method VARCHAR,
  delivery_address JSONB,
  delivery_city_code INT,
  delivery_order_id VARCHAR,
  delivery_track VARCHAR,
  delivery_status VARCHAR,
  delivery_provider_track VARCHAR,
  payment_method VARCHAR,
  payment_id VARCHAR,
  payment_status VARCHAR DEFAULT 'pending',
  customer_name VARCHAR NOT NULL,
  customer_email VARCHAR NOT NULL,
  customer_phone VARCHAR NOT NULL,
  customer_comment TEXT,
  created_at TIMESTAMP DEFAULT now(),
  updated_at TIMESTAMP DEFAULT now()
);
